Added functions to create HCP, Patient or Device and their related user
icure/icure-e2e-test-setup pull request #4
Opened 2022-09-22 13:14 UTC by TestaDiRapa

2022-09-26 09:02 UTC, lisatr2812 commented
Following GitFlow, when you want to create a PR, it is your feature branch to merge into develop. 
Develop should never be merged into master. Releases branches are created from develop and merged into master. 
For more details see : https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

2022-09-26 09:56 UTC, lisatr2812 requested changes

2022-09-26 09:56 UTC, lisatr2812 commented on docker/create_group/Dockerfile
> +                '1796980233375ccd113c972d946b2c4a7892e4f69c60684cfa730150047f9c0b',\
I'm afraid of this passwordHash and the groupPassword put in clear here : Isn't it logged somewhere when starting the docker ?

2022-09-26 09:56 UTC, lisatr2812 commented on lib/ts/src/creation.ts
> +export const createPatient = async (
Rename to `createPatientUser`

2022-09-26 09:56 UTC, lisatr2812 commented on lib/ts/src/creation.ts
>    adminPassword: string,
Rename to `createMasterHcpUser`

2022-09-26 09:56 UTC, lisatr2812 commented on lib/ts/src/creation.ts
> +  privateKey: string,
I would add a User DTO and an optional Patient DTO in argument, so that we can add the provided information to the created Patient. 
I'm thinking about the mobile phone registration of the user for example, where we need to create the user with specific additional information

2022-09-26 09:56 UTC, lisatr2812 commented on lib/ts/src/creation.ts
> +  const api = await Api(host, userLogin, token, webcrypto as any, fetchImpl)
To init patient delegation from himself to himself, I would create another method. Otherwise : 
- it is not clear that the provided publicKey & private key must be the ones of the user; 
- You will be able to optionally generate a keyPair in your method here;
- A second method will allow you to return the updated patient, taking the patient API in argument which will be clearer (or any other API to create the delegation you need);

2022-09-26 09:56 UTC, lisatr2812 commented on lib/ts/src/creation.ts
> +export const createHealthcareParty = async (api: Apis, userLogin: string, userToken: string, publicKey: string): Promise<AuthenticationResult> => {
Rename to `createHealthcarePartyUser`

2022-09-26 09:56 UTC, lisatr2812 commented on lib/ts/src/creation.ts
>      new HealthcareParty({
I would add a UserDto and an optional HealthcareParty DTO in function arguments, so that we can also provide specific information

2022-09-26 09:56 UTC, lisatr2812 commented on lib/ts/test/test-creation-kraken.ts
> +    const { publicKey } = await api.cryptoApi.RSA.generateKeyPair()
I would even put the key generation into the createHealthcareParty step, so that we don't need to take care of that either. 
For more flexibility, we can make it optional : If nothing is provided, the method creates the keyPair, otherwise it uses the provided one

2022-09-26 09:56 UTC, lisatr2812 commented on lib/ts/src/creation.ts
>  export interface MasterCredentials {
We could even make this class more general and return it for each user we are creating (master or not master)

2022-09-26 09:56 UTC, lisatr2812 commented on lib/ts/test/test-creation-oss.ts
> +    await setup('test/scratch', process.env.OSS_DOCKER_URL!)
If really needed, add a Run Configuration Example in the README with all values we need to provide

2022-09-26 10:09 UTC, TestaDiRapa commented on docker/create_group/Dockerfile
> +                '1796980233375ccd113c972d946b2c4a7892e4f69c60684cfa730150047f9c0b',\
Actually I think that this Docker could be removed, as we do not need right now: we can just initialize the group and the users in the tests both for the docker and the acceptance without relying on another docker for the creation.

2022-09-26 10:13 UTC, TestaDiRapa commented on lib/ts/src/creation.ts
> +  privateKey: string,
I have a doubt: shoun't these method provide the bare minimum to initialize the test environment? If you need something different, you can just create it directly in the tests.

2022-09-26 10:22 UTC, TestaDiRapa commented on lib/ts/src/creation.ts
>      new HealthcareParty({
For this I have the same doubt as for the patient

2022-09-26 10:26 UTC, TestaDiRapa commented on lib/ts/src/index.ts
> +export const setupCouchDb = async (couchDbUrl: string) => {
I thought that providing the url would make the method simpler if we are not in a docker. Even if we have multiple couchDB, we would have to call the method multiple times anyways, or not?

2022-09-26 10:27 UTC, TestaDiRapa commented on lib/ts/test/test-creation-kraken.ts
> +    await setup('test/scratch', process.env.KRAKEN_DOCKER_URL!)
It may not always be local, because I have to pull the compose for the arm processor from another branch of the  repository

2022-09-26 11:17 UTC, TestaDiRapa commented on lib/ts/test/test-creation-kraken.ts
> +    masterCredentials = await createMasterHcp('john', 'LetMeIn', groupId, fetch)
No, because the password we provide is hashed during the login process

2022-09-26 11:34 UTC, TestaDiRapa commented on lib/ts/src/creation.ts
> +  const api = await Api(host, userLogin, token, webcrypto as any, fetchImpl)
I have a doubt: If we divide this into two methods, we will get two methods that are strongly coupled, as they must be called together and in this context we don't want to call just one of them for some reason. 
I agree on the clarity about the parameter, but I think it will the same also if we separate the methods, because they will have basically the same interface

2022-09-26 11:52 UTC, TestaDiRapa commented on lib/ts/test/test-creation-kraken.ts
> +    const api = await Api('http://127.0.0.1:16044/rest/v1', masterCredentials.login, masterCredentials.password, webcrypto as any, fetch)
The fact is that you should instatiate this only once, to create the other "basic" users. In addition, if we want to return the api, we would return the ones without the keys, as adding the keys requires a local storage, right? 
So in this case we would return the api and the public and private key and I think it would be less clean than returning the credentials as the other methods

2022-09-27 09:27 UTC, lisatr2812 commented on lib/ts/src/creation.ts
> +  privateKey: string,
I agree

2022-09-27 09:30 UTC, lisatr2812 commented on lib/ts/test/test-creation-kraken.ts
> +    const api = await Api('http://127.0.0.1:16044/rest/v1', masterCredentials.login, masterCredentials.password, webcrypto as any, fetch)
Yes, you're right, because moreover, we're using credentials & keys to create the MedTechAPI in medtech-sdk so it's better to keep it this way

2022-09-27 09:43 UTC, lisatr2812 commented on lib/ts/test/test-creation-kraken.ts
> +    masterCredentials = await createMasterHcp('john', 'LetMeIn', groupId, fetch)
I'm concerned about the fact the credentials are in clear : For acceptance env, we'll put it in a GitHub secret when using it, but we need to make sure credentials won't be logged during the dedicated GitHub action. 
We can do a test during a GitHub action with a dedicated admin user and scratch it if any problem

2022-09-27 09:46 UTC, lisatr2812 commented on docker/create_group/Dockerfile
> +                '1796980233375ccd113c972d946b2c4a7892e4f69c60684cfa730150047f9c0b',\
Ok

2022-09-27 09:50 UTC, lisatr2812 commented on lib/ts/src/creation.ts
> +  const api = await Api(host, userLogin, token, webcrypto as any, fetchImpl)
Let's keep it that way, to cover 80% of the test cases we have today, as those methods are totally optional. 
If we want a specific initialised patient, we can still do it into the dedicated project, as we have everything needed

2022-09-27 09:51 UTC, lisatr2812 commented on lib/ts/src/creation.ts
>      new HealthcareParty({
Ok I agree

2022-09-27 09:52 UTC, lisatr2812 commented on lib/ts/src/index.ts
> +export const setupCouchDb = async (couchDbUrl: string) => {
True + if we want multiple CouchDB instances, we'll need to check the code afterwards which is limiting CouchDB to a single node. So let's effectively keep it simple for now

2022-09-27 10:00 UTC, closed without merging

2022-09-27 10:02 UTC, lisatr2812 commented
To avoid breaking GitFlow standard, we'll not merge the PR to let the code on development branch and create a dedicated release branch to merge in master.